Repository unlicense/unlicense.org, pull requests merged in 2018-09, with the labels that each got.

#54 Use https for link to unlicense.org
  README.md
Labels: site

#49 Prefer https to fetch tumblr button
  wiki/index
Labels: bug

#35 Fix missing underlines on https links
  .templates/document.html
Labels: bug

#30 add BitWasp, OTRXMPPChannel and OTRXMPPLogger; convert all Github http l...
  wiki/index
Labels: site

#50 Remove extra spaces
  wiki/index
Labels: site

#55 Change UNLICENSE file to use HTTPS link
  static/UNLICENSE
Labels: feature
