Repository unlicense/unlicense.org, pull requests merged in 2024-11, with the labels that each got.

#78 fix a broken link
  wiki/index
Labels: bug

#65 Explain usage in package registries such as npm or PyPI
  wiki/index
Labels: feature

#66 Remove google plus buttons
  wiki/index
Labels: bug

#67 Remove tracking buttons
  wiki/index
Labels: site
